id: I606D8464
legacy_id: P001801
ocr_import_info:
  bdrc_scan_id: W1KG18139
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T22:38:47'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T06:31:23.121381+00:00'
last_modified: 2022-08-27 14:33:51.204003
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG18139
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG18139
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལམ་རིམ་བླ་མ་བརྒྱུད་པའི་རྣམ་ཐར།
  author: ཚེ་མཆོག་གླིང་ཡོངས་འཛིན་ཡེ་ཤེས་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.9128320762640929
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG18167:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG18167
      total_pages: 770
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG18167.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9046570828791016
    legacy_id: v001
  I1KG18168:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG18168
      total_pages: 810
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG18168.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9200649734218115
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
