id: P001801
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 10:22:27.127555
source_metadata:
  id: bdr:W1KG18139
  title: ལམ་རིམ་བླ་མ་བརྒྱུད་པའི་རྣམ་ཐར།
  author: ''
  volumes:
    8eed8f74cbda45b8bb192652a682cb0e:
      image_group_id: I1KG18167
      title: ''
      volume_number: 1
      total_pages: 770
      base_file: v001.txt
    e786666df955430c8a44104e2be04ac2:
      image_group_id: I1KG18168
      title: ''
      volume_number: 2
      total_pages: 810
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
